// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonHelp: typeof import('~icons/carbon/help')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonSailboatOffshore: typeof import('~icons/carbon/sailboat-offshore')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    LogosVue: typeof import('~icons/logos/vue')['default']
    Post: typeof import('./components/Post.vue')['default']
    README: typeof import('./components/README.md')['default']
    ReloadPrompt: typeof import('./components/ReloadPrompt.vue')['default']
  }
}

export { }
